title: Manuale di Scambi
email: tartarughe@scambi.org
description: >- # this means to ignore newlines until "baseurl:"
    Istruzioni per la costruzione di un festival
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manuale.scambi.org" # the base hostname & protocol for your site, e.g. http://example.com
author: "APS Oltre"
publisher: "APS Oltre"
twitter_username: scambifestival
github_username: aps-oltre
git_repository: manuale
future: true
profile: true
livereload: true
strict_front_matter: true
exclude:
  - riordinare/
keep_files:
  - images/
  - assets/

theme: minima
social:
  name: APS Oltre
twitter:
  username: scambifestival
  card: summary

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-redirect-from
  - jekyll-debug
  - jekyll-watch
  - jekyll-email-protect

sass:
  style: compressed
permalink: /:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      lang: "it"
